Python 3.8 is supported by pyarrow so installing it.The associated error is given in description
  File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/components/v1/components.py", line 123, in create_instance

    raise StreamlitAPIException(

streamlit.errors.StreamlitAPIException: To use Custom Components in Streamlit, you need to install

PyArrow. Unfortunately, PyArrow does not yet support Python 3.9.

You can either switch to Python 3.8 with an environment manager like PyEnv, or stay on 3.9 by

[installing Streamlit with conda](https://discuss.streamlit.io/t/note-installation-issues-with-python-3-9-and-streamlit/6946):

`conda install -c conda-forge streamlit`